/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectStatus = IDL.Variant({
  'active' : IDL.Null,
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const ProjectInput = IDL.Record({
  'status' : ProjectStatus,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'config' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProjectStatus,
  'isDeleted' : IDL.Bool,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'config' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func([ProjectInput], [IDL.Nat], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
  'getTotalProjectsCreated' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProjectCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserProjects' : IDL.Func([IDL.Principal], [IDL.Vec(Project)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProject' : IDL.Func([IDL.Nat, ProjectInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectStatus = IDL.Variant({
    'active' : IDL.Null,
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const ProjectInput = IDL.Record({
    'status' : ProjectStatus,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'config' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProjectStatus,
    'isDeleted' : IDL.Bool,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'config' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func([ProjectInput], [IDL.Nat], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
    'getTotalProjectsCreated' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProjectCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUserProjects' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProject' : IDL.Func([IDL.Nat, ProjectInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };